### ISSUE TITLE
simple click on folder's name to open

### ISSUE THREAD

**Issue by DhammaCharts** [lunu-bounir/tree.js#1]
Hi, I've not been able to modify the code from [tree.js](https://github.com/lunu-bounir/tree.js/blob/master/tree.js) to allow user to open a folder when clicking on a node (folder name). You can see [the website I'm building here](https://www.dhammacharts.org/quartz/) where the folder named "notes" appears at the top left.

For the moment one needs to double click on the folder name or simple click on the arrow to open the folder. I cannot see where double click is called in the code.

I would like to simple click the folder's name to open it.

Thanks ! my code for this site is in [this github branch](https://github.com/DhammaCharts/quartz/tree/new-layout). It is generated with Hugo

**Comment by lunu-bounir** [comment]
There is no need to modify the code. Just manually open on `select` event.

```js
tree.on('select', e => {
  if (e.tagName === 'SUMMARY') {
    tree.open(e.parentElement);
  }
});
```

**Comment by DhammaCharts** [comment]
Thank you it works !
