### ISSUE TITLE
use click on node (file) to redirect to page

### ISSUE THREAD

**Issue by DhammaCharts** [lunu-bounir/tree.js#2]
When I try to do a redirect when clicking on a node I get into an infinite reload. I tried code like this :

 ```
 // click on node go to page
      tree.on('select', e => {
        if (e.tagName === 'A') window.location.href = e.node.href;
      });
```

or 

```
tree.on('select', e => {
  if (e.getAttribute('href')) window.location.assign(e.getAttribute('href'))
});
```

but this always creates an infinite loop as it looks that there is some `select` that are made when loading the page. 

Indeed, when I use tree.browse(), it does select node and the redirect get triggered. (see my other issue for browse usage) This single line triggers a 'select' : 

`    tree.browse(a => true)`

Is there another way to do it ?

Thanks

**Comment by lunu-bounir** [comment]
The `select` event is fired multiple times since, during the browsing, all parent nodes get selected. You need to perform a redirect when the browse is over.

Either update the code that browses the node or use something like this:

```js
{
  let timeout;

  const navigate = href => location.replace(href);
  tree.on('select', e => {
    if (e.tagName === 'A') {
      clearTimeout(timeout);
      timeout = setTimeout(navigate, 100, e.node.href);
    }
  });
}

```

**Comment by DhammaCharts** [comment]
Very nice ! I used [this method](https://stackoverflow.com/a/65227522/15473629) to create the following code :

```
function openTree(){
          var p = new Promise(function(success) {
            // open the tree at the current page
            tree.browse(a => {
              if(crumbNoBase.indexOf(a.node.id) !== -1) {
                  return true;
              }
              return false
            });
            success();
          });
        return p;
    }

 function redirectOnClick(){
      let p = openTree();
      p.then(function(s) {
        // click on node to go to page
        tree.on('select', e => {
          if (  e.node.type     == 'page'
            &&  e.node.href+'/' != pathWindow)
            window.location.href = e.node.href;
        });
      });
  }

 redirectOnClick()
```
