### ISSUE TITLE
highlighting the node of the current page in tree

### ISSUE THREAD

**Issue by DhammaCharts** [lunu-bounir/tree.js#3]
I'm also looking for highlighting the node of the current page in the tree. I've manage to expand the folders at the curent page with :

```
const crumb = pathWindow.split("/");
const crumbNoBase = crumb.splice(2, crumb.length-3)

tree.browse(a => {
      if(crumbNoBase.indexOf(a.node.name.replace(/ /g,'-')) !== -1) {
        return true;
      }
      return false
    });
```

But I cannot change the style of that specific node when `a.node.name == crumbNoBase.pop()`. It breaks the tree.browse function when I do it.

Is there any documentation about the methods on tree ?

my best guess so far was : 

```
tree.browse(a => {
      const name = a.node.name.replace(/ /g,'-');
      const pageName = crumbNoBase.slice(-1)[0]

      if(crumbNoBase.indexOf(name) !== -1) {
        if (pageName == name) {
          a.style.color = 'red'
        }
        return true;
      }
      return false
    });
```
This works if the page is at the top of a folder, but not if the page is below the top. It seems that tree.browse doesn't browse each "file" node.

Thanks, it is very helpful for our project !

**Comment by lunu-bounir** [comment]
> This works if the page is at the top of a folder, but not if the page is below the top. 

I am not sure what the problem is. You can alter one of the examples to provide the complete code so that I can check. Note that the `browse` method selects the node for you. This node has the `selected` class name. Use CSS to alter the highlighting.

```
.select-tree .selected {...}
```

**Comment by DhammaCharts** [comment]
OK, when modifying one of your exemple, I spotted that one of my file name was the same as the folder name above and so triggered the test for a true. And as long as there is a `return true` on a file, the tree.browse() stops.  

FYI, here is the modified part of your example 1 :

```
var structure = [{
  name: 'file 1'
}, {
  name: 'file 2'
}, {
  name: 'zero',
  open: false,
  type: Tree.FOLDER,
  selected: true,
  children: [{
    name: 'file 1/1'
  }, {
    name: 'file 1/2'
  }, {
    name: 'alpha',
    type: Tree.FOLDER,
    children: [{
      name: 'beta',
      type: Tree.FOLDER,
      children: [{
        name: 'gamma',
        type: Tree.FOLDER,
        children: [{
          name: 'gamma'
        }, {
          name: 'page two'
        }
        , {
          name: 'page three'
        }]
      }]
    }]
  }]
}, {
  name: 'folder 2 (asynced)',
  type: Tree.FOLDER,
  asynced: true
}];

const crumb=['zero','alpha', 'beta', 'gamma', 'page two']

  tree.browse(a => {
    console.log(a.node);
      if (crumb.indexOf(a.node.name) !== -1) {
      return true;
    }
    return false;
  });


```

this code highlight the **gamma** file instead of intended **page two**. To fix it, I used unique ids for each nodes and run the test on ids

**Comment by DhammaCharts** [comment]
One last question considering this point. Do you know how to disable the auto scroll to highlighted node ? When tree.browse() finishes and highlight the node, the page automatically scroll down to it to show the node. This is not intended in our app, especially on mobile where the tree opens below the content. 

Thank you very much for all your help, you can check out https://quartz.jzhao.xyz/ to see the project

**Comment by lunu-bounir** [comment]
Build a custom tree and use it instead:

```js
class CustomTree extends Tree {
  focus() {
    console.log('skipped');
  }
}
```

**Comment by DhammaCharts** [comment]
Ok thank you I will give this a try and come back to you.

**Comment by DhammaCharts** [comment]
It worked perfectly thank you 

```
class CustomTree extends Tree {
    focus() {
      console.log('skipped');
    }
  }

 var tree = new CustomTree(document.getElementById('tree'), {
  });
```
