### ISSUE TITLE
Click on node Mobile not working

### ISSUE THREAD

**Issue by DhammaCharts** [lunu-bounir/tree.js#4]
I am very happy with the behaviour of the tree on Desktop browser. See [here](https://www.dhammacharts.org/dhammas/) for current projet.

I realize however that on my iPhone with safari, it is not possible to click on a page link. clicking on a folder or a button is ok, but not clicking on a file node (or page link in my case)

I've made a test from your exemple 1, it is live [here](https://www.dhammacharts.org/tree.js/example%20-%201/example.html)  and works well on desktop browser. It gives an alert when clicking on button, folder node and file node. But **on Mobile (safari iPhone) clicking on the file node doesn't trigger any alert.**

the code I've added to your exemple is ([full code here](https://github.com/DhammaCharts/tree.js/blob/master/example%20-%201/example.js)) :

```
document.getElementById('browse-1').addEventListener('click', () => {
  alert("test alert")
});

tree.on('select', e => {
  if (e.tagName === 'SUMMARY') {
    tree.open(e.parentElement);
  }
});

function openTree(){
      var p = new Promise(function(success) {
        // open the tree at the current page
        tree.browse(a => {
          if (a.node.name.startsWith('folder 1') || a.node.name === 'file 1/1/1/1/2') {
              return true;
          }
          return false
        });
        success();
      });
    return p;
}

function redirectOnClick(){
    let p = openTree();
    p.then(function(s) {
      // click on node to go to page
      tree.on('select', e => {
          // window.location.href = 'www.google.com';
          alert("Link working !");
      });
    });
}

redirectOnClick()
```

Thanks for your help !

**Comment by lunu-bounir** [comment]
> tree.on('select', e => ..

Do not re-register events inside a callback. You are registering a new one with each click. Rewrite the code to use a single listener. Most likely in your code, the `select` event is fired before the promise resolves.

```js
let lastSelected;
tree.on('select', e => {
  lastSelected = e.parentElement;
});

```

**Comment by DhammaCharts** [comment]
I don't know if I understood well. I took out the listener like so :

``` js
let treeIsOpen = false;
tree.on('select', e => {
  if (e.tagName === 'SUMMARY') tree.open(e.parentElement);
  if (treeIsOpen) alert("Link working !");
});

function openTree(){
      var p = new Promise(function(success) {
        // open the tree at the current page
        tree.browse(a => {
          if (a.node.name.startsWith('folder 1') || a.node.name === 'file 1/1/1/1/2') {
              return true;
          }
          return false
        });
        success();
      });
    return p;
}

function setOpenTree(){
    let p = openTree();
    p.then(function() {
      treeIsOpen = true;
    });
}

setOpenTree()
```

but I still get the same faulty behaviour on my iPhone. The test is [live here](https://www.dhammacharts.org/tree.js/example%20-%201/example.html) and works well on desktop browser.

Thank you again for your help.

**Comment by lunu-bounir** [comment]
> But on Mobile (safari iPhone) clicking on the file node doesn't trigger any alert.

It works on Android. Since I don't have an iPhone to test, you need to debug the issue yourself.

**Comment by DhammaCharts** [comment]
Yes, I have just tested on Android and you are right it works. Thanks !
I'll try to debug safari 
Thank you again for all your help !

**Comment by DhammaCharts** [comment]
This is actually a problem for clicking on button with safari. I have same problem with safari desktop

https://stackoverflow.com/questions/41972388/ios-safari-double-tap-button-issue

I can double click page node, but simple click doesn't trigger on.("click") at all for page node
