### ISSUE TITLE
How to Update the Tree View After Renaming or Deleting Nodes with Async Server Browsing

### ISSUE THREAD

**Issue by surfskidude** [lunu-bounir/tree.js#7]
I've implemented the async feature to browse my server's file system and have successfully created a context menu that allows users to rename, delete, and create new resources. While adding new folders and files is functioning correctly, I need help figuring out how to update the tree view when renaming a node or deleting a file/directory.

Specifically, I need assistance with the following:

1. Rename a node in the tree after the user has modified its name using the context menu.
2. Refreshing the tree view to accurately display the remaining files/directories after a deletion has occurred.

Any guidance or suggestions on how to achieve these tasks would be greatly appreciated!

**Comment by lunu-bounir** [comment]
I added two examples to rename and delete a node.  See `example - 1` directory.

**Comment by surfskidude** [comment]
Excellent, thank you.
